In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")

CSV_FILE = "sales_data.csv"

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
class SalesDataAnalyzer:
    def __init__(self, file_path=None):
        self.data = pd.DataFrame()
        self.file_path = None
        self.last_plot = None

        if file_path:
            self.load_data(file_path)

    def __del__(self):
        pass

analyzer = SalesDataAnalyzer()
print("SalesDataAnalyzer object created successfully!")

SalesDataAnalyzer object created successfully!

In [3]:
def load_data(self, file_path):
    try:
        self.data = pd.read_csv(file_path)
        self.file_path = file_path
        print("Dataset loaded successfully!")
        print("Rows:", self.data.shape[0])
        print("Columns:", self.data.shape[1])
        print("\nColumn names:")
        print(self.data.columns.tolist())
        display(self.data.head())
    except FileNotFoundError:
        print(f"Error: File '{file_path}' was not found. Check the filename and folder.")
    except pd.errors.EmptyDataError:
        print("Error: The CSV file is empty.")
    except Exception as e:
        print("Error loading dataset:", e)

SalesDataAnalyzer.load_data = load_data
analyzer.load_data(CSV_FILE)

Dataset loaded successfully!
Rows: 152
Columns: 7

Column names:
['SalesID', 'Date', 'Product', 'Region', 'Sales', 'Profit', 'Year']

   SalesID        Date   Product Region   Sales  Profit  Year
0      101  2024-01-01  Keyboard  North  1260.0   214.0  2023
1      102  2024-01-02     Mouse  North   479.0   314.0  2025
2      103  2024-01-03    Tablet  North  1572.0   491.0  2023
3      104  2024-01-04     Mouse  North   696.0   249.0  2025
4      105  2024-01-05     Mouse   East   501.0    98.0  2023

In [4]:
def explore_data(self):
    if self.data.empty:
        print("Please load a dataset first.")
        return

    while True:
        print("\n=== Explore Data ===")
        print("1. First 5 rows")
        print("2. Last 5 rows")
        print("3. Column names")
        print("4. Data types")
        print("5. Dataset information")
        print("6. Shape")
        print("7. Return")

        choice = input("Enter your choice: ").strip()

        if choice == "1":
            display(self.data.head())
        elif choice == "2":
            display(self.data.tail())
        elif choice == "3":
            print(self.data.columns.tolist())
        elif choice == "4":
            display(self.data.dtypes.to_frame("Data Type"))
        elif choice == "5":
            self.data.info()
        elif choice == "6":
            print("Rows:", self.data.shape[0], "| Columns:", self.data.shape[1])
        elif choice == "7":
            break
        else:
            print("Invalid choice. Enter a number from 1 to 7.")

SalesDataAnalyzer.explore_data = explore_data

In [5]:
def clean_data(self):
    if self.data.empty:
        print("Please load a dataset first.")
        return

    print("Missing values before cleaning:")
    display(self.data.isna().sum().to_frame("Missing Values"))
    print("Duplicate rows before cleaning:", self.data.duplicated().sum())

    for column in self.data.columns:
        if self.data[column].isna().any():
            if pd.api.types.is_numeric_dtype(self.data[column]):
                mean_value = self.data[column].mean()
                if pd.notna(mean_value):
                    self.data[column] = self.data[column].fillna(mean_value)
            else:
                modes = self.data[column].mode(dropna=True)
                if not modes.empty:
                    self.data[column] = self.data[column].fillna(modes.iloc[0])

    duplicates_removed = int(self.data.duplicated().sum())
    self.data.drop_duplicates(inplace=True)

    print("\nCleaning completed.")
    print("Duplicate rows removed:", duplicates_removed)
    print("Missing values remaining:", int(self.data.isna().sum().sum()))
    display(self.data.isna().sum().to_frame("Missing Values Remaining"))

SalesDataAnalyzer.clean_data = clean_data

In [6]:
def mathematical_operations(self):
    if self.data.empty:
        print("Please load a dataset first.")
        return

    numeric_columns = self.data.select_dtypes(include=np.number).columns.tolist()
    if not numeric_columns:
        print("No numeric columns found.")
        return

    print("Numeric columns:", numeric_columns)
    column = input("Enter a numeric column name: ").strip()
    if column not in numeric_columns:
        print("Invalid numeric column.")
        return

    try:
        number = float(input("Enter a number to use in the operation: "))
    except ValueError:
        print("Please enter a valid number.")
        return

    operation = input("Choose operation (add, subtract, multiply, divide, square): ").strip().lower()
    values = self.data[column]

    if operation == "add":
        result = values + number
    elif operation == "subtract":
        result = values - number
    elif operation == "multiply":
        result = values * number
    elif operation == "divide":
        if number == 0:
            print("Cannot divide by zero.")
            return
        result = values / number
    elif operation == "square":
        result = values ** 2
    else:
        print("Unknown operation.")
        return

    output = self.data[[column]].copy()
    output["Result"] = result
    display(output.head(10))
    print("First 10 results displayed.")

SalesDataAnalyzer.mathematical_operations = mathematical_operations

In [7]:
def combine_data(self, other_file=None):
    if self.data.empty:
        print("Please load the main dataset first.")
        return

    if other_file is None:
        other_file = input("Enter path of the second CSV file: ").strip()

    try:
        other = pd.read_csv(other_file)
        print("Choose combine method:")
        print("1. Concatenate rows (same/similar columns)")
        print("2. Merge using a common column")
        choice = input("Enter choice: ").strip()

        if choice == "1":
            combined = pd.concat([self.data, other], ignore_index=True, sort=False)
        elif choice == "2":
            common = [c for c in self.data.columns if c in other.columns]
            if not common:
                print("No common columns available for merging.")
                return
            print("Common columns:", common)
            key = input("Enter the column to merge on: ").strip()
            if key not in common:
                print("Invalid merge column.")
                return
            combined = pd.merge(self.data, other, on=key, how="outer", suffixes=("_left", "_right"))
        else:
            print("Invalid choice.")
            return

        print("Combined dataset preview:")
        display(combined.head())
        print("Combined shape:", combined.shape)
        save = input("Replace current data with combined data? (y/n): ").strip().lower()
        if save == "y":
            self.data = combined
            print("Current dataset updated.")
    except FileNotFoundError:
        print("Second CSV file not found.")
    except Exception as e:
        print("Error combining datasets:", e)

SalesDataAnalyzer.combine_data = combine_data

In [8]:
def split_data(self):
    if self.data.empty:
        print("Please load a dataset first.")
        return

    print("Available columns:", self.data.columns.tolist())
    column = input("Enter column to split by (e.g., Region or Product): ").strip()
    if column not in self.data.columns:
        print("Column not found.")
        return

    for value, group in self.data.groupby(column, dropna=False):
        label = "missing" if pd.isna(value) else str(value)
        safe_label = "".join(ch if ch.isalnum() or ch in "-_" else "_" for ch in label)
        print(f"\n--- {column}: {label} | rows: {len(group)} ---")
        display(group.head())
        save = input(f"Save this group to split_{safe_label}.csv? (y/n): ").strip().lower()
        if save == "y":
            group.to_csv(f"split_{safe_label}.csv", index=False)
            print("Saved.")

SalesDataAnalyzer.split_data = split_data

In [9]:
def search_sort_filter(self):
    if self.data.empty:
        print("Please load a dataset first.")
        return

    while True:
        print("\n=== Search, Sort, Filter ===")
        print("1. Search text in a column")
        print("2. Filter numeric values")
        print("3. Sort by a column")
        print("4. Filter by an exact value")
        print("5. Return")
        choice = input("Enter choice: ").strip()

        if choice == "1":
            column = input(f"Column {self.data.columns.tolist()}: ").strip()
            if column not in self.data.columns:
                print("Column not found.")
                continue
            term = input("Text to search: ").strip()
            result = self.data[self.data[column].astype(str).str.contains(term, case=False, na=False)]
            display(result.head(50))
            print("Matching rows:", len(result))

        elif choice == "2":
            numeric = self.data.select_dtypes(include=np.number).columns.tolist()
            print("Numeric columns:", numeric)
            column = input("Numeric column: ").strip()
            if column not in numeric:
                print("Invalid numeric column.")
                continue
            try:
                threshold = float(input("Show rows where value is greater than or equal to: "))
                result = self.data[self.data[column] >= threshold]
                display(result.head(50))
                print("Matching rows:", len(result))
            except ValueError:
                print("Enter a valid number.")

        elif choice == "3":
            column = input(f"Sort by column {self.data.columns.tolist()}: ").strip()
            if column not in self.data.columns:
                print("Column not found.")
                continue
            order = input("Ascending order? (y/n): ").strip().lower() == "y"
            display(self.data.sort_values(column, ascending=order, na_position="last").head(50))

        elif choice == "4":
            column = input(f"Column {self.data.columns.tolist()}: ").strip()
            if column not in self.data.columns:
                print("Column not found.")
                continue
            value = input("Exact value to match: ").strip()
            result = self.data[self.data[column].astype(str).str.lower() == value.lower()]
            display(result.head(50))
            print("Matching rows:", len(result))

        elif choice == "5":
            break
        else:
            print("Invalid choice.")

SalesDataAnalyzer.search_sort_filter = search_sort_filter

In [10]:
def aggregate_functions(self):
    if self.data.empty:
        print("Please load a dataset first.")
        return

    numeric = self.data.select_dtypes(include=np.number).columns.tolist()
    if not numeric:
        print("No numeric columns found.")
        return

    print("Numeric columns:", numeric)
    column = input("Enter numeric column: ").strip()
    if column not in numeric:
        print("Invalid column.")
        return

    series = self.data[column]
    print("Sum:", series.sum())
    print("Mean:", series.mean())
    print("Median:", series.median())
    print("Minimum:", series.min())
    print("Maximum:", series.max())
    print("Count:", series.count())
    print("Standard deviation:", series.std())

    group_column = input("Optional: enter a category column to group by (or press Enter to skip): ").strip()
    if group_column:
        if group_column not in self.data.columns:
            print("Column not found.")
        else:
            display(self.data.groupby(group_column, dropna=False)[column].agg(["sum", "mean", "count", "min", "max"]))

SalesDataAnalyzer.aggregate_functions = aggregate_functions

In [11]:
def statistical_analysis(self):
    if self.data.empty:
        print("Please load a dataset first.")
        return

    numeric_data = self.data.select_dtypes(include=np.number)
    if numeric_data.empty:
        print("No numeric columns found.")
        return

    print("Descriptive statistics:")
    display(numeric_data.describe().T)
    print("\nVariance:")
    display(numeric_data.var().to_frame("Variance"))
    print("\nStandard deviation:")
    display(numeric_data.std().to_frame("Standard Deviation"))
    print("\n25th, 50th, and 75th percentiles:")
    display(numeric_data.quantile([0.25, 0.50, 0.75]).T)

SalesDataAnalyzer.statistical_analysis = statistical_analysis

In [12]:
def create_pivot_table(self):
    if self.data.empty:
        print("Please load a dataset first.")
        return

    numeric = self.data.select_dtypes(include=np.number).columns.tolist()
    if not numeric:
        print("No numeric columns found.")
        return

    print("Columns:", self.data.columns.tolist())
    index_col = input("Enter row/group column (e.g., Region): ").strip()
    value_col = input(f"Enter numeric values column {numeric}: ").strip()
    if index_col not in self.data.columns or value_col not in numeric:
        print("Invalid column selection.")
        return

    columns_col = input("Optional column for pivot columns (press Enter to skip): ").strip()
    try:
        if columns_col:
            if columns_col not in self.data.columns:
                print("Pivot column not found.")
                return
            pivot = pd.pivot_table(self.data, index=index_col, columns=columns_col,
                                   values=value_col, aggfunc="sum", fill_value=0)
        else:
            pivot = pd.pivot_table(self.data, index=index_col, values=value_col,
                                   aggfunc=["sum", "mean", "count"])
        display(pivot)
    except Exception as e:
        print("Could not create pivot table:", e)

SalesDataAnalyzer.create_pivot_table = create_pivot_table

In [13]:
def numpy_operations(self):
    if self.data.empty:
        print("Please load a dataset first.")
        return

    numeric = self.data.select_dtypes(include=np.number).columns.tolist()
    if not numeric:
        print("No numeric columns found.")
        return

    print("Numeric columns:", numeric)
    column = input("Choose a numeric column: ").strip()
    if column not in numeric:
        print("Invalid column.")
        return

    array = self.data[column].dropna().to_numpy()
    print("NumPy array (first 10 values):", array[:10])
    print("First value:", array[0] if len(array) else "Array is empty")
    print("First five values:", array[:5])
    print("Values from index 2 to 6:", array[2:7])
    print("Array + 10:", array[:10] + 10)
    print("Array * 2:", array[:10] * 2)
    print("Array mean:", np.mean(array))
    print("Array standard deviation:", np.std(array))
    print("Array variance:", np.var(array))
    print("25th percentile:", np.percentile(array, 25))
    print("75th percentile:", np.percentile(array, 75))

SalesDataAnalyzer.numpy_operations = numpy_operations

In [14]:
def visualize_data(self):
    if self.data.empty:
        print("Please load a dataset first.")
        return

    numeric = self.data.select_dtypes(include=np.number).columns.tolist()
    if not numeric:
        print("No numeric columns found.")
        return

    categorical = self.data.select_dtypes(include=["str","object", "category", "bool"]).columns.tolist()
    date_columns = self.data.select_dtypes(include=["datetime64[ns]"]).columns.tolist()

    print("\n=== Data Visualization ===")
    print("1. Bar plot")
    print("2. Line plot")
    print("3. Scatter plot")
    print("4. Pie chart")
    print("5. Histogram")
    print("6. Stack plot")
    print("7. Seaborn box plot")
    print("8. Seaborn heatmap")
    print("9. Multiple subplots")
    choice = input("Enter your choice: ").strip()

    try:
        if choice == "1":
            print("Category columns:", categorical)
            category = input("Category column for x-axis: ").strip()
            value = input(f"Numeric column for y-axis {numeric}: ").strip()
            if category not in self.data.columns or value not in numeric:
                print("Invalid column.")
                return
            plot_data = self.data.groupby(category, dropna=False)[value].sum().sort_values(ascending=False)
            plot_data.plot(kind="bar", title=f"{value} by {category}")
            plt.xlabel(category)
            plt.ylabel(value)
            plt.xticks(rotation=45)
            plt.tight_layout()

        elif choice == "2":
            x = input(f"X-axis column {self.data.columns.tolist()} (or press Enter for row index): ").strip()
            y = input(f"Y-axis numeric column {numeric}: ").strip()
            if y not in numeric or (x and x not in self.data.columns):
                print("Invalid column.")
                return
            if x:
                plot_data = self.data[[x, y]].dropna().sort_values(x)
                plt.plot(plot_data[x], plot_data[y], marker="o", label=y)
                plt.xlabel(x)
            else:
                plt.plot(self.data[y].reset_index(drop=True), marker="o", label=y)
                plt.xlabel("Row")
            plt.ylabel(y)
            plt.title(f"{y} trend")
            plt.legend()
            plt.xticks(rotation=45)

        elif choice == "3":
            print("Numeric columns:", numeric)
            x = input("X-axis numeric column: ").strip()
            y = input("Y-axis numeric column: ").strip()
            if x not in numeric or y not in numeric:
                print("Invalid numeric column.")
                return
            plt.scatter(self.data[x], self.data[y], alpha=0.7)
            plt.xlabel(x)
            plt.ylabel(y)
            plt.title(f"{y} vs {x}")

        elif choice == "4":
            print("Category columns:", categorical)
            category = input("Category column: ").strip()
            if category not in self.data.columns:
                print("Invalid column.")
                return
            counts = self.data[category].fillna("Missing").value_counts()
            if len(counts) > 10:
                counts = counts.head(10)
                print("Showing top 10 categories.")
            plt.pie(counts.values, labels=counts.index.astype(str), autopct="%1.1f%%")
            plt.title(f"Distribution of {category}")

        elif choice == "5":
            column = input(f"Numeric column {numeric}: ").strip()
            if column not in numeric:
                print("Invalid numeric column.")
                return
            sns.histplot(self.data[column].dropna(), kde=True)
            plt.xlabel(column)
            plt.title(f"Distribution of {column}")

        elif choice == "6":
            print("Category columns:", categorical)
            category = input("Category column for groups: ").strip()
            value = input(f"Numeric column {numeric}: ").strip()
            if category not in self.data.columns or value not in numeric:
                print("Invalid column.")
                return
            grouped = self.data.groupby(category, dropna=False)[value].sum().sort_values(ascending=False).head(6)
            plt.stackplot(range(len(grouped)), grouped.values, labels=grouped.index.astype(str))
            plt.xticks(range(len(grouped)), grouped.index.astype(str), rotation=45)
            plt.xlabel(category)
            plt.ylabel(value)
            plt.title(f"Stack plot of {value}")
            plt.legend(loc="upper left")

        elif choice == "7":
            column = input(f"Numeric column {numeric}: ").strip()
            if column not in numeric:
                print("Invalid numeric column.")
                return
            sns.boxplot(x=self.data[column])
            plt.title(f"Box plot of {column}")

        elif choice == "8":
            corr = self.data[numeric].corr()
            sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f")
            plt.title("Correlation Heatmap")

        elif choice == "9":
            selected = numeric[:4]
            if not selected:
                print("No numeric columns found.")
                return
            fig, axes = plt.subplots(len(selected), 1, figsize=(8, 4 * len(selected)))
            if len(selected) == 1:
                axes = [axes]
            for ax, column in zip(axes, selected):
                ax.hist(self.data[column].dropna(), bins=15)
                ax.set_title(f"Distribution of {column}")
                ax.set_xlabel(column)
            plt.tight_layout()

        else:
            print("Invalid choice.")
            return

        self.last_plot = plt.gcf()
        plt.tight_layout()
        plt.show()
        print("Visualization generated successfully.")

    except Exception as e:
        plt.close("all")
        print("Could not generate visualization:", e)

SalesDataAnalyzer.visualize_data = visualize_data

In [15]:
def save_visualization(self):
    if self.last_plot is None:
        print("Create a visualization first using option 6.")
        return

    filename = input("Enter filename (e.g., sales_chart.png): ").strip()
    if not filename:
        print("Filename cannot be empty.")
        return
    if not filename.lower().endswith((".png", ".jpg", ".jpeg", ".pdf")):
        filename += ".png"

    try:
        self.last_plot.savefig(filename, dpi=300, bbox_inches="tight")
        print(f"Visualization saved successfully as {filename}")
    except Exception as e:
        print("Error saving visualization:", e)

SalesDataAnalyzer.save_visualization = save_visualization

In [16]:
def export_report(self):
    if self.data.empty:
        print("Please load a dataset first.")
        return

    print("1. Export full dataset to CSV")
    print("2. Export descriptive statistics to CSV")
    choice = input("Enter choice: ").strip()

    try:
        if choice == "1":
            filename = input("Output filename (e.g., cleaned_sales.csv): ").strip() or "cleaned_sales.csv"
            self.data.to_csv(filename, index=False)
            print("Dataset exported to", filename)
        elif choice == "2":
            filename = input("Output filename (e.g., sales_statistics.csv): ").strip() or "sales_statistics.csv"
            stats = self.data.select_dtypes(include=np.number).describe().T
            stats.to_csv(filename)
            print("Statistics exported to", filename)
        else:
            print("Invalid choice.")
    except Exception as e:
        print("Export failed:", e)

SalesDataAnalyzer.export_report = export_report

In [17]:
def run_menu(self):
    while True:
        print("\n" + "=" * 18 + " Data Analysis & Visualization Program " + "=" * 18)
        print("1. Load Dataset")
        print("2. Explore Data")
        print("3. Clean Data")
        print("4. Mathematical Operations")
        print("5. Combine with Another CSV")
        print("6. Split Data")
        print("7. Search, Sort, Filter")
        print("8. Aggregation Functions")
        print("9. Statistical Analysis")
        print("10. Create Pivot Table")
        print("11. NumPy Operations")
        print("12. Data Visualization")
        print("13. Save Visualization")
        print("14. Export Dataset or Report")
        print("15. Exit")
        print("=" * 70)

        choice = input("Enter your choice: ").strip()

        if choice == "1":
            path = input(f"CSV file path [{self.file_path or CSV_FILE}]: ").strip()
            self.load_data(path or self.file_path or CSV_FILE)
        elif choice == "2":
            self.explore_data()
        elif choice == "3":
            self.clean_data()
        elif choice == "4":
            self.mathematical_operations()
        elif choice == "5":
            self.combine_data()
        elif choice == "6":
            self.split_data()
        elif choice == "7":
            self.search_sort_filter()
        elif choice == "8":
            self.aggregate_functions()
        elif choice == "9":
            self.statistical_analysis()
        elif choice == "10":
            self.create_pivot_table()
        elif choice == "11":
            self.numpy_operations()
        elif choice == "12":
            self.visualize_data()
        elif choice == "13":
            self.save_visualization()
        elif choice == "14":
            self.export_report()
        elif choice == "15":
            print("Thank you for using the Data Analysis & Visualization Program!")
            break
        else:
            print("Invalid choice. Please enter a number from 1 to 15.")

SalesDataAnalyzer.run_menu = run_menu
print("Menu function added successfully!")

Menu function added successfully!

In [18]:
analyzer = SalesDataAnalyzer()
analyzer.load_data(CSV_FILE)
analyzer.run_menu()

Dataset loaded successfully!
Rows: 152
Columns: 7

Column names:
['SalesID', 'Date', 'Product', 'Region', 'Sales', 'Profit', 'Year']

   SalesID        Date   Product Region   Sales  Profit  Year
0      101  2024-01-01  Keyboard  North  1260.0   214.0  2023
1      102  2024-01-02     Mouse  North   479.0   314.0  2025
2      103  2024-01-03    Tablet  North  1572.0   491.0  2023
3      104  2024-01-04     Mouse  North   696.0   249.0  2025
4      105  2024-01-05     Mouse   East   501.0    98.0  2023

================== Data Analysis & Visualization Program ==================
1. Load Dataset
2. Explore Data
3. Clean Data
4. Mathematical Operations
5. Combine with Another CSV
6. Split Data
7. Search, Sort, Filter
8. Aggregation Functions
9. Statistical Analysis
10. Create Pivot Table
11. NumPy Operations
12. Data Visualization
13. Save Visualization
14. Export Dataset or Report
15. Exit
======================================================================

Enter your choice:  1
CSV file path [sales_data.csv]:  sales_data

Error: File 'sales_data' was not found. Check the filename and folder.

================== Data Analysis & Visualization Program ==================
1. Load Dataset
2. Explore Data
3. Clean Data
4. Mathematical Operations
5. Combine with Another CSV
6. Split Data
7. Search, Sort, Filter
8. Aggregation Functions
9. Statistical Analysis
10. Create Pivot Table
11. NumPy Operations
12. Data Visualization
13. Save Visualization
14. Export Dataset or Report
15. Exit
======================================================================

Enter your choice:  2

=== Explore Data ===
1. First 5 rows
2. Last 5 rows
3. Column names
4. Data types
5. Dataset information
6. Shape
7. Return

Enter your choice:  1

   SalesID        Date   Product Region   Sales  Profit  Year
0      101  2024-01-01  Keyboard  North  1260.0   214.0  2023
1      102  2024-01-02     Mouse  North   479.0   314.0  2025
2      103  2024-01-03    Tablet  North  1572.0   491.0  2023
3      104  2024-01-04     Mouse  North   696.0   249.0  2025
4      105  2024-01-05     Mouse   East   501.0    98.0  2023

=== Explore Data ===
1. First 5 rows
2. Last 5 rows
3. Column names
4. Data types
5. Dataset information
6. Shape
7. Return

Enter your choice:  7

================== Data Analysis & Visualization Program ==================
1. Load Dataset
2. Explore Data
3. Clean Data
4. Mathematical Operations
5. Combine with Another CSV
6. Split Data
7. Search, Sort, Filter
8. Aggregation Functions
9. Statistical Analysis
10. Create Pivot Table
11. NumPy Operations
12. Data Visualization
13. Save Visualization
14. Export Dataset or Report
15. Exit
======================================================================

Enter your choice:  15

Thank you for using the Data Analysis & Visualization Program!